### ISSUE TITLE
Get provider

### ISSUE THREAD

**Issue by raffaem** [moehmeni/syncedlyrics#23]
I would like to get the provider for the lyrics, but I don't know how without breaking [the API](https://github.com/moehmeni/syncedlyrics/blob/7b32de623df78c98c4d31a479e37fc9c6f4f1181/syncedlyrics/__init__.py#L18).

Maybe have another function, and the existing function calling the new function and returning just the lyrics out of it?

**Comment by moehmeni** [comment]
You mean the the name of the provider when you get the lyrics?
If so, you can capture the provider name from the logs.
```py
import io
import logging
import syncedlyrics

syncedlyrics.logger.setLevel(logging.INFO)
stream = io.StringIO()
syncedlyrics.logger.addHandler(logging.StreamHandler(stream))

syncedlyrics.search("...")

print(stream.getvalue().split("on ")[1])
```

**Comment by raffaem** [comment]
I think this is slower.

What about a new class `Lyrics` that holds both lyrics and provider, a function `lookup` that return `Lyrics`, and the `search` function just call `lookup` and return just the lyrics?

**Comment by moehmeni** [comment]
I know it's a bit messy but I don't want to break the simple API since the main goal is to get the lyrics. It's not slow either if you benchmark it.
```py
t1 = time.time()
provider = stream.getvalue().split("on ")[1].strip()
t2 = time.time()

print(round(t2 - t1, 5))
print(provider)
```
```
0.0
Musixmatch
```
