### ISSUE TITLE
Request: Enhanced LRC Support

### ISSUE THREAD

**Issue by twentyonekoalas** [moehmeni/syncedlyrics#24]
It would be great to have an option to download the enhanced lrc if available.

**Comment by moehmeni** [comment]
Thanks for the suggestion. Do you know any source providing the format? I think it's only the YouTube transcripts for karaokes?

**Comment by twentyonekoalas** [comment]
I believe musixmatch has word-level timings. I saw it was provided by the spicetify lyrics-plus addon. 

https://github.com/spicetify/spicetify-cli/blob/master/CustomApps/lyrics-plus/ProviderMusixmatch.js

**Comment by moehmeni** [comment]
You can check with `--enhanced` flag. With latest clone but, new version is not yet published.

**Comment by rahaaatul** [comment]
Do you know what android music player can play the word by word lyrics?

**Comment by IlIllIl** [comment]
> Do you know what android music player can play the word by word lyrics?

I've found this one: https://github.com/Moriafly/SaltPlayerSource
