### ISSUE TITLE
Add provider Genius.com

### ISSUE THREAD

**Issue by deedy5** [moehmeni/syncedlyrics#27]
1) request api for url 
https://genius.com/api/search/multi?per_page=5&q=macarena
see `artist_names`, `full_title`, `url`
2) parse url
https://genius.com/Los-del-rio-macarena-lyrics

**Comment by moehmeni** [comment]
Thanks for the suggestion.
It works on my machine but fails the tests when querying step 1. I tested with both requests and curl_cffi. Logs showed it gets 403 status code for step 1.

**Comment by deedy5** [comment]
Try with curl-cffi, but use [`impersonate`](https://github.com/yifeikong/curl_cffi/blob/4d0982cbd4f49abe6f4075bba17a0400d548b4da/curl_cffi/requests/session.py#L614)
self.session = requests.Session(**impersonate="chrome"**)

**Comment by moehmeni** [comment]
If I use curl-cffi, I get an error mentioned in #29 in local. Also, [the workflow test](https://github.com/moehmeni/syncedlyrics/actions/runs/8302017395) (with `impersonate`) could not pass as well.

**Comment by deedy5** [comment]
```python3
curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (55) Recv failure: Connection reset by peer. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
``` 
look https://curl.se/libcurl/c/libcurl-errors.html
```python
CURLE_SEND_ERROR (55)

Failed sending network data. 
```
[def get_lrc()](https://github.com/moehmeni/syncedlyrics/blob/0c39d0fe28532a7cfa865546fab0bee00e8cc4eb/syncedlyrics/providers/genius.py#L13)
Unclear problem. Are you sure a cookie is needed here? 
Try to add logging before each line that returns None to see what happens.

**Comment by moehmeni** [comment]
I commented out the tests for Genius for now, but in action, can you please confirm it works with `-p Genius`?

**Comment by deedy5** [comment]
1) `megalobiz.com` site's not working anymore, it says :`megalobiz.com has expired`,
2) `genius` tests work.
