### ISSUE TITLE
No Github release for 0.10.1

### ISSUE THREAD

**Issue by pekkarr** [moehmeni/syncedlyrics#40]
The latest version on PyPI is 0.10.1, but the Github release and git tag for that version is missing. Currently the latest Github release is 0.10.0.

Could 0.10.1 be added to the releases as well?

**Comment by moehmeni** [comment]
Since it was only a small bug fix and just after the 0.10.0 release I did not post it and mentioned the change in the end of that release. Is it important for something?

**Comment by pekkarr** [comment]
Thanks for the quick response!

> Is it important for something?

For the [Arch Linux AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-syncedlyrics#n17) we use the git tag to pull the correct source code archive from Github, as Github provides source archives automatically at `https://github.com/moehmeni/syncedlyrics/archive/refs/tags/v${pkgver}.tar.gz`. This requires that the repository has the specific version tag.

We could pull the source code using the commit ID as well, but version tags are easier to deal with for us.

Additionally, people might use tools like [nvchecker](https://github.com/lilydjwg/nvchecker) to monitor the latest release of the software, and if nvchecker is configured to monitor Github releases it won't notice the new version (nvchecker can also be configured to get the version from PyPI which gives the correct version currently).

**Comment by moehmeni** [comment]
Thanks for explanation, I released a new one.

**Comment by pekkarr** [comment]
Thanks, the AUR package is now updated to 0.10.1
